'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store={get:(k)=>{try{return localStorage.getItem(k)}catch{return null}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch{}}};
const fragment=new URLSearchParams(location.hash.slice(1));
let token=fragment.get('token');try{token=token||sessionStorage.getItem('omnaraToken');if(token)sessionStorage.setItem('omnaraToken',token)}catch{}
history.replaceState(null,'',location.pathname);
let vault=null,campaigns=[],tab='atlas',dirty=false,generation=0,loading=0,saving=false;
let selectedClaim=null,selectedSource=null,compareSource='',claimQuery='',claimFilter='all',sourceQuery='',sourceFilter='all',reportFile='report.md',nativeFile='campaign.json';
const viewNames={atlas:'Evidence atlas',sources:'Reading room',frontier:'Open questions',report:'Synthesis',frame:'Inquiry & scope',claims:'Edit claim',files:'Native files'};
function status(message){$('#status').textContent=message}
function error(message){$('#notice-text').textContent=message;$('#notice').hidden=false;status(message)}
async function act(fn){try{return await fn()}catch(e){error(e.message);return null}}
async function api(path,data={}){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':token||''},body:JSON.stringify(data)});if(!r.ok){let message;try{message=(await r.json()).error}catch{message='The local service did not return a usable response.'}throw Error(message||'The local service could not complete this action.')}return (r.headers.get('content-type')||'').includes('application/json')?r.json():r.blob()}
function campaign(){try{return JSON.parse(vault.files['campaign.json'])}catch{throw Error('campaign.json contains invalid JSON. Open Native files to repair it; your draft is still here.')}}
function rows(name){try{return (vault.files[name]||'').split('\n').filter(s=>s.trim()).map(s=>JSON.parse(s))}catch{throw Error(name+' contains invalid JSONL. Open Native files to repair it; your draft is still here.')}}
function put(name,value){vault.files[name]=typeof value==='string'?value:JSON.stringify(value,null,2)+'\n';dirty=true;generation++;vault.semantic_review={state:'not-current',errors:['Unsaved changes need current review after saving.']};saveState();if($('#review-state'))$('#review-state').textContent='Current semantic review: unestablished after unsaved edits';$$('[data-tone=good]').forEach(el=>el.dataset.tone='gap');status('Unsaved changes · Save vault to keep them')}
function jsonl(name,value){put(name,value.map(x=>JSON.stringify(x)).join('\n')+'\n')}
function saveState(){$('#save').disabled=!dirty||saving;$('#save').textContent=saving?'Saving…':dirty?'Save vault •':'Saved'}
function dateLabel(value){const d=new Date(value);return Number.isNaN(d.valueOf())?'Date not recorded':d.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function sourceTitle(s){return s?.title||s?.url||s?.identifier||'Missing source record'}
function safeUrl(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function recordedDisposition(c){return c.semantic_audit||c.support||c.evidence_status||'Unreviewed'}
function reviewedClaim(c){return vault?.semantic_review?.state==='current'&&!dirty?vault.semantic_review.claims?.find(x=>x.claim_id===c.id):null}
function disposition(c){const review=reviewedClaim(c);return review?review.treatment:recordedDisposition(c)+' · historical/unbound'}
function judgmentField(c){return c.semantic_audit?'semantic_audit':c.support?'support':c.evidence_status?'evidence_status':'support'}
function tone(c){const review=reviewedClaim(c);return review?.treatment==='supported'?'good':!review||review.treatment==='unresolved'?'gap':'neutral'}
function needsReview(c){const review=reviewedClaim(c);return !review||review.treatment==='unresolved'}
function tags(s){return `<div class="state-tags">${(s.states||[]).map(x=>`<span class="state-tag ${['deeply-read','cited'].includes(x)?'earned':''}">${esc(x)}</span>`).join('')}</div>`}
function locator(s){const value=s.url||s.identifier||'No locator recorded',url=safeUrl(value);return `<p class="locator">${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(value)} ↗</a>`:esc(value)}</p>`}
function metadata(s){return `<div class="metadata">${[['Type',s.source_type],['Period',s.period||s.date],['Accessed',s.accessed_date],['Custody',s.custody]].filter(x=>x[1]).map(([k,v])=>`<span>${esc(k)}<b>${esc(v)}</b></span>`).join('')}</div>`}
// Native documents are always text: no raw HTML or executable Markdown.
function inline(text){const fragments=String(text).split(/(\[[^\]\n]+\]\(https?:\/\/[^\s)]+\)|\[S[\w-]+\]|\*\*[^*]+\*\*|`[^`]+`)/g);return fragments.map(piece=>{const link=piece.match(/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)$/);if(link&&safeUrl(link[2]))return `<a href="${esc(safeUrl(link[2]))}" target="_blank" rel="noopener noreferrer">${esc(link[1])}</a>`;if(/^\[S[\w-]+\]$/.test(piece))return `<button class="cite" data-read="${esc(piece.slice(1,-1))}">${esc(piece)}</button>`;if(piece.startsWith('**')&&piece.endsWith('**'))return '<strong>'+esc(piece.slice(2,-2))+'</strong>';if(piece.startsWith('`')&&piece.endsWith('`'))return '<code>'+esc(piece.slice(1,-1))+'</code>';return esc(piece)}).join('')}
function tableCells(line){return line.trim().replace(/^\||\|$/g,'').split(/(?<!\\)\|/).map(x=>x.trim().replace(/\\\|/g,'|'))}
function manuscript(text){const lines=String(text||'').split('\n');let out='',paragraph=[],listType='',code=null;const flush=()=>{if(paragraph.length){out+='<p>'+inline(paragraph.join('\n'))+'</p>';paragraph=[]}if(listType){out+='</'+listType+'>';listType=''}};for(let i=0;i<lines.length;i++){const line=lines[i];if(/^```/.test(line)){flush();if(code===null)code=[];else{out+='<pre>'+esc(code.join('\n'))+'</pre>';code=null}continue}if(code!==null){code.push(line);continue}if(/^\s*\|/.test(line)){flush();const table=[];while(i<lines.length&&/^\s*\|/.test(lines[i]))table.push(tableCells(lines[i++]));i--;const hasHeader=table.length>1&&table[1].every(x=>/^:?-+:?$/.test(x));out+='<div class="table-scroll" tabindex="0" aria-label="Scrollable evidence table"><table>';table.forEach((row,j)=>{if(hasHeader&&j===1)return;const cell=hasHeader&&j===0?'th':'td';out+='<tr>'+row.map(x=>`<${cell}>${inline(x)}</${cell}>`).join('')+'</tr>'});out+='</table></div>';continue}const h=line.match(/^(#{1,6})\s+(.*)/);if(h){flush();const level=Math.min(4,h[1].length+1);out+=`<h${level}>${inline(h[2])}</h${level}>`;continue}const li=line.match(/^\s*(?:([-*])|\d+\.)\s+(.*)/);if(li){if(paragraph.length){out+='<p>'+inline(paragraph.join('\n'))+'</p>';paragraph=[]}const type=li[1]?'ul':'ol';if(type!==listType){if(listType)out+='</'+listType+'>';out+='<'+type+'>';listType=type}out+='<li>'+inline(li[2])+'</li>';continue}if(!line.trim()){flush();continue}if(line.startsWith('> ')){flush();out+='<blockquote>'+inline(line.slice(2))+'</blockquote>';continue}if(/^[-*_]{3,}$/.test(line.trim())){flush();out+='<hr>';continue}if(listType){out+='</'+listType+'>';listType=''}paragraph.push(line)}flush();if(code!==null)out+='<pre>'+esc(code.join('\n'))+'</pre>';return out||'<p class="quiet-state">Nothing recorded here yet.</p>'}
function coverage(text){const lines=String(text||'').split('\n'),tables=[],rest=[];for(let i=0;i<lines.length;i++){if(/^\s*\|/.test(lines[i])&&i+1<lines.length&&tableCells(lines[i+1]).every(x=>/^:?-+:?$/.test(x))){const headings=tableCells(lines[i]);i+=2;const entries=[];while(i<lines.length&&/^\s*\|/.test(lines[i]))entries.push(tableCells(lines[i++]));i--;tables.push({headings,entries})}else rest.push(lines[i])}return {tables,rest:rest.join('\n')}}
function card(c){return `<button class="campaign-card" data-key="${esc(c.key)}"><span class="eyebrow">${esc(c.phase)}${c.status&&c.status!==c.phase?' / '+esc(c.status):''}</span><h3>${esc(c.title)}</h3><p class="small">${esc(c.inquiry)}</p><span class="card-tail">${c.error?'Needs repair · ':''}${c.source_count!==undefined?`${c.source_count} sources · ${c.claim_count} claims · `:''}Open investigation ↗</span></button>`}
function drawLibrary(){for(const [search,target] of [['#campaign-search','#list'],['#picker-search','#picker-list']]){const query=$(search).value.toLowerCase(),matching=campaigns.filter(c=>(c.title+' '+c.inquiry).toLowerCase().includes(query));$(target).innerHTML=matching.map(card).join('')||`<p class="quiet-state">${campaigns.length?'No matching investigation. Try a shorter search.':'Your first question starts here. Create an investigation or import a native campaign.'}</p>`}$('#library-count').textContent=campaigns.length+' investigations'}
async function list(){const data=await api('list');campaigns=data.campaigns.sort((a,b)=>(b.updated_at||'').localeCompare(a.updated_at||''));$('#root').textContent='Research home · '+data.data_root;drawLibrary()}
function canLeave(){return !dirty||confirm('This vault has unsaved changes. Discard them and continue? Cancel to save or download your draft first.')}
async function open(key){if(saving){error('Wait for the current save to finish before changing investigations.');return}if(!canLeave())return;const sequence=++loading;status('Opening investigation…');$('#room').setAttribute('aria-busy','true');try{const loaded=await api('load',{key});if(sequence!==loading)return;vault=loaded;dirty=false;generation++;selectedClaim=null;selectedSource=null;compareSource='';claimQuery='';claimFilter='all';sourceQuery='';sourceFilter='all';tab='atlas';reportFile='report.md';nativeFile='campaign.json';store.set('omnaraCampaign',key);$('#picker').close();$('#empty').hidden=true;$('#room').hidden=false;$('#notice').hidden=true;render();window.scrollTo({top:0,behavior:'instant'});status('Opened native campaign · changes are saved only when you choose Save vault')}finally{$('#room').removeAttribute('aria-busy')}}
function library(){if(!canLeave())return;dirty=false;vault=null;loading++;$('#room').hidden=true;$('#empty').hidden=false;saveState();drawLibrary();status('Campaign library')}
function navigate(next,source){tab=next;if(source){selectedSource=source;sourceFilter='all';sourceQuery='';compareSource=''}render();window.scrollTo({top:0,behavior:'instant'});status(viewNames[tab]||tab)}
function render(){if(!vault)return;saveState();document.body.dataset.view=tab;try{const c=campaign();$('#title').textContent=c.title;$('#phase').textContent=c.phase+' / '+c.status;$('#question').textContent=c.canonical_inquiry;$('#dated').textContent='Updated '+dateLabel(c.updated_at);$('#review-state').textContent='Current semantic review: '+(vault.semantic_review?.state||'unreviewed')+' · declared review, not independent certification';const ss=rows('source-ledger.jsonl');$('#counts').innerHTML='<p>RECORDED STATES · NOT A COMPLETION SCORE</p>'+['discovered','inspected','opened','deeply-read','cited','inaccessible'].map(s=>`<button class="state-count" data-state="${s}" title="Show ${s} sources"><b>${ss.filter(x=>(x.states||[]).includes(s)).length}</b><span>${s}</span></button>`).join('');$('#validation-summary').textContent=vault.validation.length?'Vault integrity · '+vault.validation.length+' issue(s)':'Vault integrity · native structure checked';$('#validation').textContent=vault.validation.length?vault.validation.join('\n'):'Native structure was valid at the last load or save. Review state is separately bound to saved content; declared review does not establish reviewer independence or source truth.';$$('#tabs button').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false'));const builders={atlas:renderAtlas,sources:renderReader,frontier:renderFrontier,report:renderReport,frame:renderFrame,claims:renderClaimEditor,files:renderFiles};(builders[tab]||renderAtlas)(c)}catch(e){$('#title').textContent='Native records need repair · '+vault.key;$('#phase').textContent='needs repair';$('#question').textContent='Original question is in the damaged native file.';$('#counts').innerHTML='';$('#review-state').textContent='Current review unavailable until records are repaired';error(e.message);tab='files';renderFiles()}}
function matchingClaims(){return rows('claim-ledger.jsonl').filter(c=>(c.id+' '+c.claim+' '+disposition(c)).toLowerCase().includes(claimQuery.toLowerCase())&&(claimFilter==='all'||claimFilter==='unlinked'&&!(c.source_ids||[]).length||claimFilter==='unreviewed'&&needsReview(c)))}
function renderAtlas(c){
  const claims=rows('claim-ledger.jsonl');
  if(!claims.some(x=>x.id===selectedClaim)) selectedClaim=claims[0]?.id||null;
  const linked=claims.filter(x=>(x.source_ids||[]).length).length;
  const unreviewed=claims.filter(needsReview).length;
  const citedSources=[...new Set(claims.flatMap(x=>x.source_ids||[]))];
  const unlinkedSources=rows('source-ledger.jsonl').filter(s=>!citedSources.includes(s.id)).length;
  const concentration=citedSources.map(id=>({id,n:claims.filter(x=>(x.source_ids||[]).includes(id)).length})).sort((a,b)=>b.n-a.n)[0];
  $('#content').innerHTML=`<div class="atlas-intro"><div><p class="eyebrow">THE ARGUMENT IN VIEW · ${esc(c.phase)}</p><h2>Where does the answer rest?</h2><p>Select an assertion or follow a source across the argument. The connections are recorded citations; read the evidence before accepting the claim.</p></div><div class="atlas-summary" aria-label="Structural observations"><span><b>${linked}</b> of ${claims.length} claims cite a source</span><span><b>${unreviewed}</b> need current review</span>${unlinkedSources?`<span><b>${unlinkedSources}</b> source${unlinkedSources===1?'':'s'} without a claim link</span>`:''}${concentration&&concentration.n>1?`<span><b>${esc(concentration.id)}</b> is cited by ${concentration.n} claims</span>`:''}</div></div>
  <div class="atlas-workspace"><section class="atlas-map" aria-label="Claim and source connections"><div class="map-heading"><div><p class="eyebrow">CLAIMS ⇄ SOURCES</p><h3>Trace the argument.</h3></div><button class="secondary" data-action="new-claim">＋ Record a claim</button></div><div class="map-controls"><label>Find an assertion<input id="claim-search" type="search" value="${esc(claimQuery)}" placeholder="Claim or recorded judgment"></label><label>Show<select id="claim-filter"><option value="all">Every claim</option><option value="unlinked">Without citations</option><option value="unreviewed">Unreviewed</option></select></label></div><div id="evidence-field" class="map-canvas"></div><div class="map-legend"><span><i class="legend-link"></i> Recorded citation</span><span><i class="legend-focus"></i> Selected trail</span><span>Connection ≠ support</span></div></section>
  <aside class="atlas-inspector" aria-label="Evidence in focus"><div id="focus-claim"></div><div id="source-peek" class="source-peek"></div></aside></div>
  <div class="edge-strip"><section><p class="eyebrow"><span class="next-mark">↗</span> ${c.phase==='complete'?'REOPEN WHEN IT MATTERS':'THE NEXT CONSEQUENTIAL PASS'}</p><p class="next-copy">${esc(c.resume_point||'Name the observation that could move this inquiry forward.')}</p><button class="text-link" data-go="frontier">Explore open questions →</button></section><section><p class="eyebrow">THE BOUNDARY OF THIS PICTURE</p><p class="small">${esc(c.counter_scope||'A link records a citation, not semantic support. A full-reading state describes work performed, not what every claim earns.')}</p>${(c.blockers||[]).length?`<p class="blocker">${c.blockers.length} recorded blocker(s) · <button class="text-link" data-go="frontier">Inspect</button></p>`:''}</section></div>`;
  $('#claim-filter').value=claimFilter;
  $('#claim-search').oninput=e=>{claimQuery=e.target.value;drawEvidence()};
  $('#claim-filter').onchange=e=>{claimFilter=e.target.value;drawEvidence()};
  drawEvidence();
}
function orientClaim(){const list=$('#claim-list'),el=list?.querySelector('[aria-pressed=true]');if(!el)return;const a=el.getBoundingClientRect(),b=list.getBoundingClientRect();if(a.bottom>b.bottom)list.scrollTop+=a.bottom-b.bottom;else if(a.top<b.top)list.scrollTop+=a.top-b.top}
function drawClaims(){
  const target=$('#claim-list');if(!target)return;
  const claims=matchingClaims();
  target.innerHTML=claims.map(c=>`<button class="claim-choice" data-claim="${esc(c.id)}" aria-pressed="${c.id===selectedClaim}" data-tone="${tone(c)}"><span class="claim-id">${esc(c.id)}</span><span class="claim-copy">${esc(c.claim)}</span><span class="claim-foot"><span>${esc(disposition(c))}</span><span>${(c.source_ids||[]).length} citation${(c.source_ids||[]).length===1?'':'s'}</span></span></button>`).join('')||'<div class="blank-state">No assertions match this view. Clear the filter or record a provisional claim.</div>';
}
function drawEvidence(){
  const claims=rows('claim-ledger.jsonl'),sources=rows('source-ledger.jsonl');
  const visible=matchingClaims();
  if(!visible.some(x=>x.id===selectedClaim)){selectedClaim=visible[0]?.id||null;selectedSource=null}
  const claim=claims.find(x=>x.id===selectedClaim);
  const cited=[...new Set(visible.flatMap(c=>c.source_ids||[]))];
  if(claim) for(const id of claim.source_ids||[]) if(!cited.includes(id)) cited.unshift(id);
  const ordered=[...new Set([...(claim?.source_ids||[]),...cited])];
  const displayIds=ordered.slice(0,Math.max(32,(claim?.source_ids||[]).length));
  const sourceById=new Map(sources.map(s=>[s.id,s]));
  $('#evidence-field').innerHTML=`<div class="map-column map-claims"><div class="column-label"><span>Assertions</span><span>${visible.length} visible</span></div><div id="claim-list" class="claim-list"></div></div><svg class="map-links" aria-hidden="true"></svg><div class="map-column map-sources"><div class="column-label"><span>Cited records</span><span>${displayIds.length}${cited.length>displayIds.length?' of '+cited.length:''}</span></div><div class="map-source-list">${displayIds.map(id=>{const s=sourceById.get(id),n=claims.filter(c=>(c.source_ids||[]).includes(id)).length;return `<button class="source-node" data-peek="${esc(id)}" aria-pressed="${id===selectedSource}" ${s?'':'data-missing="true"'}><span class="source-id">${esc(id)}</span><span class="source-copy">${esc(sourceTitle(s))}</span><span class="source-reach">${s?`${n} claim${n===1?'':'s'} · ${esc((s.states||[]).includes('deeply-read')?'deeply read':(s.states||[]).at(-1)||'state unrecorded')}`:'Source record missing'}</span></button>`}).join('')||'<p class="quiet-state">No cited source records in this view. Select a claim or open the reading room.</p>'}</div></div>`;
  drawClaims();
  if(!claim){$('#focus-claim').innerHTML=claims.length?'<p class="eyebrow">NO MATCH IN THIS VIEW</p><h3>The filter leaves the field empty.</h3><p>Clear it to return to the recorded argument.</p><button data-action="clear-claim-filter">Show every claim</button>':'<p class="eyebrow">NO CLAIM RECORDED</p><h3>Begin with a testable assertion.</h3><p>Record what the evidence might establish; keep the uncertainty explicit until it has been read.</p><button data-action="new-claim">Record a claim</button>';selectedSource=null}
  else{
    if(!(claim.source_ids||[]).includes(selectedSource) && !sourceById.has(selectedSource))selectedSource=claim.source_ids?.[0]||null;
    $('#focus-claim').innerHTML=`<div class="focus-heading"><p class="eyebrow">${esc(claim.id)} / SELECTED ASSERTION</p><span class="disposition" data-tone="${tone(claim)}">${esc(disposition(claim))}</span></div><h3>${esc(claim.claim)}</h3>${claim.basis?`<p class="claim-basis">${esc(claim.basis)}</p>`:''}<p class="focus-custody">${(claim.source_ids||[]).length} recorded citation${(claim.source_ids||[]).length===1?'':'s'} · Recorded judgment is not a current-review verdict. See the review state above.</p><button class="text-link" data-action="edit-claim">Edit assertion & citations →</button>`;
  }
  drawPeek();
  requestAnimationFrame(drawConnections);
}
function drawPeek(){
  const s=rows('source-ledger.jsonl').find(x=>x.id===selectedSource);
  if(!s){$('#source-peek').innerHTML='<p class="eyebrow">SOURCE EVIDENCE</p><h3>No source to inspect.</h3><p class="small">Select a cited record or open the reading room. Missing records remain visible as gaps.</p>';return}
  const note=vault.files['notes/'+s.id+'.md']||'',excerpt=s.read_scope||note;
  const related=rows('claim-ledger.jsonl').filter(c=>(c.source_ids||[]).includes(s.id));
  $('#source-peek').innerHTML=`<div class="peek-heading"><p class="eyebrow">${esc(s.id)} / SOURCE IN FOCUS</p><h3>${esc(sourceTitle(s))}</h3>${tags(s)}${metadata(s)}</div><div class="source-reach-list"><p class="eyebrow">CITED BY ${related.length} CLAIM${related.length===1?'':'S'}</p>${related.map(c=>`<button data-claim="${esc(c.id)}">${esc(c.id)} · ${esc(c.claim)}</button>`).join('')||'<p class="small">No claim links recorded.</p>'}</div><div class="peek-body manuscript">${excerpt?manuscript(excerpt.length>2400?excerpt.slice(0,2400)+'\n\n[Excerpt continues in the reading room.]':excerpt):'<p>No full-reading note recorded. Open the reading room to document what this source establishes and where it stops.</p>'}</div>${locator(s)}<div class="actions"><button data-read="${esc(s.id)}">Read evidence →</button><button class="secondary" data-compare="${esc(s.id)}">Compare…</button></div>`;
  $$('.source-node').forEach(b=>b.setAttribute('aria-pressed',b.dataset.peek===selectedSource?'true':'false'));
}
function filteredSources(){return rows('source-ledger.jsonl').filter(s=>(s.id+' '+sourceTitle(s)+' '+(s.url||s.identifier||'')).toLowerCase().includes(sourceQuery.toLowerCase())&&(sourceFilter==='all'||sourceFilter==='awaiting'&&!(s.states||[]).some(x=>['deeply-read','excluded','duplicate','inaccessible'].includes(x))||(s.states||[]).includes(sourceFilter)))}
function renderReader(){const ss=rows('source-ledger.jsonl');if(!selectedSource)selectedSource=ss[0]?.id||null;if(compareSource===selectedSource)compareSource='';$('#content').innerHTML=`<div class="section-head"><div><p class="eyebrow">READ / TRACE / COMPARE</p><h2>Keep the evidence in view.</h2></div><button data-action="record-source">＋ Record a source</button></div><div class="reader-shell"><aside class="source-queue"><label>Find a source<input id="source-search" type="search" value="${esc(sourceQuery)}" placeholder="Title, ID or locator"></label><label>Reading queue<select id="source-filter"><option value="all">All sources (${ss.length})</option><option value="awaiting">Awaiting a full reading</option>${['discovered','inspected','opened','deeply-read','cited','inaccessible','excluded','duplicate'].map(x=>`<option value="${x}">${x}</option>`).join('')}</select></label><p id="source-result-count" class="small"></p><div id="source-list" class="source-list"></div></aside><section><div class="reader-toolbar"><label>Read alongside<select id="compare-source"><option value="">One source at a time</option>${ss.filter(x=>x.id!==selectedSource).map(x=>`<option value="${esc(x.id)}">${esc(x.id+' · '+sourceTitle(x))}</option>`).join('')}</select></label><button class="quiet" data-go="atlas">← Evidence atlas</button></div><div id="reader-pages" class="reader-pages"></div></section></div>`;$('#source-filter').value=sourceFilter;$('#compare-source').value=compareSource;$('#source-search').oninput=e=>{sourceQuery=e.target.value;drawSourceList()};$('#source-filter').onchange=e=>{sourceFilter=e.target.value;drawSourceList()};$('#compare-source').onchange=e=>{compareSource=e.target.value;drawReaderPages();status(compareSource?'Comparing '+selectedSource+' with '+compareSource:'Single-source reading')};drawSourceList();drawReaderPages()}
function drawSourceList(){const ss=filteredSources();if(!ss.some(s=>s.id===selectedSource)){selectedSource=ss[0]?.id||null;compareSource='';if($('#compare-source'))$('#compare-source').value='';drawReaderPages()}$('#source-result-count').textContent=ss.length+' sources in this view';$('#source-list').innerHTML=ss.map(s=>`<button class="source-choice" data-source="${esc(s.id)}" aria-pressed="${selectedSource===s.id}"><small>${esc(s.id)} · ${esc((s.states||[]).includes('deeply-read')?'full-reading note':(s.states||[]).join(' / '))}</small><strong>${esc(sourceTitle(s))}</strong></button>`).join('')||'<p class="quiet-state">No sources match. Change the queue or clear your search.</p>'}
function readingLeaf(s,index){if(!s)return '<article class="reading-leaf blank-state"><h2>No source record in view.</h2><p>Clear the reading filter or record a real URL or identifier to begin. Notes, provenance and claim connections will stay together here.</p><button data-action="record-source">Record a source</button></article>';const note=vault.files['notes/'+s.id+'.md']||'',cs=rows('claim-ledger.jsonl').filter(c=>(c.source_ids||[]).includes(s.id));return `<article class="reading-leaf" data-leaf="${esc(s.id)}"><p class="eyebrow">${index?'ALONGSIDE':'READING'} / ${esc(s.id)}</p><h2>${esc(sourceTitle(s))}</h2>${locator(s)}${tags(s)}${metadata(s)}<div class="section-head"><p class="eyebrow">FULL-READING EVIDENCE NOTE</p><button class="secondary" data-note-mode="${esc(s.id)}">Edit note</button></div><div class="note-projection manuscript">${note?manuscript(note):'<p class="quiet-state">No evidence note recorded. Read the source before describing what it establishes.</p>'}</div><label class="note-edit" hidden>Evidence note · Markdown<textarea class="note-editor" data-note="${esc(s.id)}">${esc(note)}</textarea></label><details class="source-details"><summary>Source details & earned states</summary><label>Title<input data-source-field="title" data-id="${esc(s.id)}" value="${esc(s.title||'')}"></label><label>URL or stable identifier<input data-source-field="${s.url?'url':'identifier'}" data-id="${esc(s.id)}" value="${esc(s.url||s.identifier||'')}"></label><label>Earned states, comma separated<input data-source-field="states" data-id="${esc(s.id)}" value="${esc((s.states||[]).join(', '))}"></label><p class="small">States describe completed work. Deeply-read requires a substantive note and its prerequisite states; Save validates them.</p>${s.read_scope?`<h4>Recorded reading scope</h4><p class="small">${esc(s.read_scope)}</p>`:''}</details>${cs.length?`<div class="related-claims"><p class="eyebrow">CITED BY ${cs.length} CLAIM${cs.length===1?'':'S'}</p>${cs.map(c=>`<button class="quiet" data-jump-claim="${esc(c.id)}">${esc(c.id)} · ${esc(c.claim)}</button>`).join('')}</div>`:''}</article>`}
function drawReaderPages(){const ss=rows('source-ledger.jsonl');$('#reader-pages').classList.toggle('comparing',!!compareSource);$('#reader-pages').innerHTML=readingLeaf(ss.find(x=>x.id===selectedSource),0)+(compareSource?readingLeaf(ss.find(x=>x.id===compareSource),1):'');$$('[data-note]').forEach(el=>el.oninput=()=>put('notes/'+el.dataset.note+'.md',el.value));$$('[data-source-field]').forEach(el=>el.oninput=()=>{const sources=rows('source-ledger.jsonl'),s=sources.find(x=>x.id===el.dataset.id);s[el.dataset.sourceField]=el.dataset.sourceField==='states'?el.value.split(',').map(x=>x.trim()).filter(Boolean):el.value;jsonl('source-ledger.jsonl',sources)})}
function renderFrontier(c){const map=coverage(vault.files['coverage-matrix.md']);$('#content').innerHTML=`<div class="frontier-top"><section class="next-pass"><p class="eyebrow">NEXT PASS / ${esc(c.phase)}</p><h2>${esc(c.resume_point||'Name the next observation that could change the answer.')}</h2><button class="secondary" data-go="frame">Plan the next pass</button></section><section><p class="eyebrow">RECORDED BLOCKERS</p>${(c.blockers||[]).length?c.blockers.map(b=>`<p class="blocker">${esc(b)}</p>`).join(''):'<p>No blockers recorded.</p>'}<p class="eyebrow">ACTIVE COVERAGE</p><div class="loci">${(c.active_loci||[]).map(x=>`<span>${esc(x)}</span>`).join('')||'<p class="small">No active loci recorded. Read the coverage boundaries below before treating the field as closed.</p>'}</div></section></div><section class="document-section"><div class="section-head"><div><p class="eyebrow">COVERAGE / WHAT REMAINS OUTSIDE THE FRAME</p><h2>Where the inquiry opens.</h2></div><button class="secondary" data-edit-file="coverage-matrix.md">Edit coverage</button></div><div class="manuscript">${manuscript(map.rest)}</div><div class="coverage-cards">${map.tables.flatMap(t=>t.entries.map((r,i)=>`<article class="coverage-card"><span class="locus-number">LOCUS ${String(i+1).padStart(2,'0')}</span><h3>${inline(r[0])}</h3><dl>${t.headings.slice(1).map((h,j)=>`<dt>${esc(h)}</dt><dd>${inline(r[j+1]||'Not recorded')}</dd>`).join('')}</dl></article>`)).join('')}</div></section><section class="document-section"><div class="section-head"><div><p class="eyebrow">RIVAL EXPLANATIONS / RECONCILIATION</p><h2>Let the evidence resist the story.</h2></div><button class="secondary" data-edit-file="contradictions.md">Edit contradictions</button></div><div class="manuscript">${manuscript(vault.files['contradictions.md'])}</div></section><details class="document-section"><summary>Query trail · recorded searches</summary><div class="manuscript">${queryTrail()}</div></details>`}
function queryTrail(){const qs=rows('query-ledger.jsonl');if(!qs.length)return '<p class="quiet-state">No queries recorded.</p>';return '<div class="table-scroll" tabindex="0" aria-label="Recorded query trail"><table><thead><tr><th>Query</th><th>Locus / route</th><th>Recorded result</th></tr></thead><tbody>'+qs.map(q=>`<tr><td>${esc(q.query||q.text||q.id||JSON.stringify(q))}</td><td>${esc(q.locus||q.route||q.engine||'Not recorded')}</td><td>${esc(q.result||q.disposition||q.notes||q.date||q.timestamp||'Not recorded')}</td></tr>`).join('')+'</tbody></table></div>'}
const reportDocs=[['report.md','Report'],['evidence-digest.md','Evidence digest'],['outline.md','Argument outline'],['citation-audit.md','Citation audit'],['campaign-summary.md','Campaign summary']];
function renderReport(){const docs=[...reportDocs,...Object.keys(vault.files).filter(x=>x.startsWith('draft/')).sort().map(x=>[x,x.replace('draft/','')])];$('#content').innerHTML=`<div class="section-head"><div><p class="eyebrow">THE PRESENT SYNTHESIS</p><h2>The argument, with its sources attached.</h2></div><button class="secondary" data-action="add-draft">＋ Add section draft</button></div><div class="report-layout"><nav class="document-tabs" aria-label="Research documents">${docs.map(([file,label])=>`<button data-document="${esc(file)}" aria-current="${reportFile===file?'page':'false'}">${esc(label)}</button>`).join('')}</nav><article class="report-paper"><div class="section-head"><span class="eyebrow">${esc(reportFile)}</span><button class="secondary" data-edit-file="${esc(reportFile)}">Edit document</button></div><div class="manuscript">${manuscript(vault.files[reportFile])}</div></article></div>`}
function renderFrame(c){$('#content').innerHTML=`<div class="section-head"><div><p class="eyebrow">INQUIRY & SCOPE</p><h2>Define what would move the answer.</h2></div><button class="secondary" data-go="atlas">← Evidence atlas</button></div><div class="frame-grid"><section class="editor-surface"><h3>The question</h3><label>Title<input id="edit-title" value="${esc(c.title)}"></label><label>Question, exactly as asked<textarea id="edit-question" rows="5">${esc(c.canonical_inquiry)}</textarea></label><div class="pair"><label>Phase<select id="edit-phase">${['framing','mapping','breadth-sweep','depth-reading','reconciliation','gap-fill','synthesis','citation-audit','review','complete','halted'].map(s=>`<option ${c.phase===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Status<select id="edit-status">${['active','complete','awaiting-evidence','awaiting-authority','capability-limited','budget-exhausted','partial-success','paused'].map(s=>`<option ${c.status===s?'selected':''}>${s}</option>`).join('')}</select></label></div></section><section class="editor-surface"><h3>The next useful pass</h3><label>Resume point<textarea id="edit-resume" rows="4">${esc(c.resume_point)}</textarea></label><label>Active coverage loci, one per line<textarea id="edit-loci">${esc((c.active_loci||[]).join('\n'))}</textarea></label><label>Blockers, one per line<textarea id="edit-blockers">${esc((c.blockers||[]).join('\n'))}</textarea></label></section></div><section class="editor-surface"><h3>Research brief / hypotheses</h3><label>Native research brief<textarea id="brief" rows="13">${esc(vault.files['research-brief.md']||'')}</textarea></label></section>`;const mapping={title:'title',question:'canonical_inquiry',phase:'phase',status:'status',resume:'resume_point',loci:'active_loci',blockers:'blockers'};Object.entries(mapping).forEach(([id,key])=>$('#edit-'+id).oninput=e=>{const updated=campaign();updated[key]=['loci','blockers'].includes(id)?e.target.value.split('\n').filter(Boolean):e.target.value;put('campaign.json',updated)});$('#brief').oninput=e=>put('research-brief.md',e.target.value)}
function renderClaimEditor(){const cs=rows('claim-ledger.jsonl'),c=cs.find(x=>x.id===selectedClaim);if(!c){tab='atlas';render();return}const field=judgmentField(c);$('#content').innerHTML=`<div class="section-head"><div><p class="eyebrow">${esc(c.id)} / CLAIM & CONNECTIONS</p><h2>Make the assertion traceable.</h2></div><button class="secondary" data-go="atlas">← Evidence atlas</button></div><section class="editor-surface"><label>Claim<textarea id="claim-text" rows="4">${esc(c.claim)}</textarea></label><div class="pair"><label>Cited source IDs, comma separated<input id="claim-sources" value="${esc((c.source_ids||[]).join(', '))}"></label><label>Recorded judgment · ${esc(field.replaceAll('_',' '))}<input id="claim-judgment" value="${esc(c[field]||'unreviewed')}"></label></div><p class="small">Source IDs create the visible connections. Keep the judgment bounded by what those sources actually establish.</p>${Object.entries(c).filter(([k])=>!['id','claim','source_ids',field].includes(k)).map(([k,v])=>`<p class="small"><strong>${esc(k.replaceAll('_',' '))}:</strong> ${esc(typeof v==='object'?JSON.stringify(v):v)}</p>`).join('')}</section>`;for(const [id,key] of [['claim-text','claim'],['claim-sources','source_ids'],['claim-judgment',field]])$('#'+id).oninput=e=>{const current=rows('claim-ledger.jsonl'),row=current.find(x=>x.id===selectedClaim);row[key]=key==='source_ids'?[...new Set(e.target.value.split(',').map(x=>x.trim()).filter(Boolean))]:e.target.value;jsonl('claim-ledger.jsonl',current)}}
function renderFiles(){if(!vault)return;const names=Object.keys(vault.files);if(!names.includes(nativeFile))nativeFile=names[0];$('#content').innerHTML=`<div class="section-head"><div><p class="eyebrow">NATIVE VAULT / EXACT TEXT</p><h2>The files behind the picture.</h2></div><button class="secondary" data-go="atlas">← Evidence atlas</button></div><div class="native-toolbar"><label>Native file<select id="native-file">${names.map(x=>`<option ${x===nativeFile?'selected':''}>${esc(x)}</option>`).join('')}</select></label><button class="secondary" data-action="add-draft">Add section draft</button></div><section class="editor-surface"><p class="small">This edits the same file your research agent uses. Save validates the campaign; invalid text stays available for repair.</p><label>${esc(nativeFile)}<textarea id="native" class="native" rows="22">${esc(vault.files[nativeFile]||'')}</textarea></label></section>`;$('#native-file').onchange=e=>{nativeFile=e.target.value;renderFiles()};$('#native').oninput=e=>put(nativeFile,e.target.value)}
function saveBlob(blob,filename){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function download(action,filename){if(dirty)throw Error('Save vault before exporting. Handoffs and exports use the saved native records.');saveBlob(await api(action,{key:vault.key}),filename);status('Downloaded '+filename)}
async function save(){if(!vault||saving)return;const submitted=structuredClone(vault),atGeneration=generation;saving=true;saveState();try{const saved=await api('save',submitted);if(vault?.key!==submitted.key)return;if(generation===atGeneration){vault=saved;dirty=false;render();status('Saved native vault · previous files retained in local history')}else{vault.revision=saved.revision;status('Submitted edits saved · later changes remain unsaved')}$('#notice').hidden=true;await list()}finally{saving=false;saveState()}}
function showCreate(){if(!canLeave())return;$('#picker').close();$('#create').showModal()}
function showImport(){if(!canLeave())return;$('#picker').close();$('#import-dialog').showModal()}
async function submitForm(form,action,values){const button=form.querySelector('[type=submit]');button.disabled=true;form.querySelector('.form-error').textContent='';try{const loaded=await api(action,values);vault=loaded;dirty=false;generation++;selectedClaim=null;selectedSource=null;compareSource='';claimQuery='';sourceQuery='';claimFilter='all';sourceFilter='all';tab='atlas';reportFile='report.md';nativeFile='campaign.json';store.set('omnaraCampaign',loaded.key);form.closest('dialog').close();form.reset();$('#empty').hidden=true;$('#room').hidden=false;$('#notice').hidden=true;render();await list();status(action==='create'?'Investigation created · frame the inquiry or record your first source':'Imported a validated copy of the campaign')}catch(e){form.querySelector('.form-error').textContent=e.message}finally{button.disabled=false}}
$('#createform').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);act(()=>submitForm(e.target,'create',{title:f.get('title'),question:f.get('question')}))};
$('#importform').onsubmit=e=>{e.preventDefault();act(()=>submitForm(e.target,'import',{path:new FormData(e.target).get('path')}))};
$('#sourceform').onsubmit=e=>{e.preventDefault();act(()=>{const f=new FormData(e.target),ss=rows('source-ledger.jsonl'),id='S'+String(Math.max(0,...ss.map(x=>Number(x.id.slice(1))||0))+1).padStart(3,'0');ss.push({id,title:f.get('title'),url:f.get('locator'),states:['discovered']});jsonl('source-ledger.jsonl',ss);selectedSource=id;sourceQuery='';sourceFilter='all';compareSource='';$('#record-dialog').close();e.target.reset();navigate('sources')})};
$('#content').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;act(()=>{const d=b.dataset;if(d.go){navigate(d.go);return}if(d.claim){if(!matchingClaims().some(x=>x.id===d.claim)){claimFilter='all';claimQuery='';$('#claim-filter').value='all';$('#claim-search').value=''}const previousScroll=$('#claim-list').scrollTop;selectedClaim=d.claim;drawClaims();$('#claim-list').scrollTop=previousScroll;orientClaim();drawEvidence();const selected=$$('.claim-choice').find(x=>x.dataset.claim===selectedClaim);selected?.focus({preventScroll:true});$('#evidence-field').scrollIntoView({block:'nearest'});status('Selected '+selectedClaim);return}if(d.peek){selectedSource=d.peek;$$('[data-peek]').forEach(node=>node.setAttribute('aria-pressed',node.dataset.peek===selectedSource));drawPeek();status('Evidence preview · '+selectedSource);return}if(d.read){navigate('sources',d.read);return}if(d.compare){navigate('sources',d.compare);$('#compare-source').focus();return}if(d.source){const previousScroll=$('#source-list').scrollTop;selectedSource=d.source;if(compareSource===selectedSource)compareSource='';renderReader();$('#source-list').scrollTop=previousScroll;$$('.source-choice').find(x=>x.dataset.source===selectedSource)?.focus({preventScroll:true});return}if(d.jumpClaim){selectedClaim=d.jumpClaim;claimFilter='all';claimQuery='';tab='atlas';render();return}if(d.document){reportFile=d.document;renderReport();return}if(d.editFile){nativeFile=d.editFile;navigate('files');return}if(d.noteMode){const leaf=b.closest('.reading-leaf'),label=leaf.querySelector('.note-edit'),projection=leaf.querySelector('.note-projection'),editing=label.hidden;label.hidden=!editing;projection.hidden=editing;b.textContent=editing?'Read note':'Edit note';if(editing)label.querySelector('textarea').focus();else projection.innerHTML=manuscript(vault.files['notes/'+d.noteMode+'.md']);return}if(d.action==='clear-claim-filter'){claimFilter='all';claimQuery='';renderAtlas(campaign());return}if(d.action==='record-source')$('#record-dialog').showModal();if(d.action==='edit-claim')navigate('claims');if(d.action==='new-claim'){const cs=rows('claim-ledger.jsonl'),id='C'+String(Math.max(0,...cs.map(x=>Number(x.id.slice(1))||0))+1).padStart(3,'0');cs.push({id,claim:'New provisional claim',source_ids:[],support:'unreviewed'});jsonl('claim-ledger.jsonl',cs);selectedClaim=id;navigate('claims')}if(d.action==='add-draft'){const n=prompt('Section filename, for example 01-introduction.md');if(!n)return;if(!/^[a-zA-Z0-9_-]+\.md$/.test(n))throw Error('Use letters, numbers, hyphens or underscores, ending in .md.');nativeFile='draft/'+n;if(vault.files[nativeFile]!==undefined)throw Error('That section already exists. Open it from Native files.');put(nativeFile,'# '+n.replace(/\.md$/,'').replaceAll('-',' ')+'\n');navigate('files')}})});
for(const target of ['#list','#picker-list'])$(target).onclick=e=>{const b=e.target.closest('[data-key]');if(b)act(()=>open(b.dataset.key))};
$('#counts').onclick=e=>{const b=e.target.closest('[data-state]');if(b){sourceFilter=b.dataset.state;sourceQuery='';tab='sources';render()}};
$('#tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b)act(()=>navigate(b.dataset.tab))};
$('#campaign-search').oninput=drawLibrary;$('#picker-search').oninput=drawLibrary;
$('#campaigns').onclick=()=>{$('#picker').showModal();$('#picker-search').focus()};
$('#home').onclick=library;$('#back-library').onclick=library;$('#new').onclick=showCreate;$('#picker-new').onclick=showCreate;$('#import').onclick=showImport;$('#picker-import').onclick=showImport;
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#dismiss-notice').onclick=()=>$('#notice').hidden=true;
$('#retry').onclick=()=>act(list);$('#save').onclick=()=>act(save);$('#reload').onclick=()=>act(()=>open(vault.key));$('#scope').onclick=()=>navigate('frame');$('#native-files').onclick=()=>navigate('files');
$('#draft-backup').onclick=()=>{if(vault)saveBlob(new Blob([JSON.stringify({key:vault.key,files:vault.files},null,2)],{type:'application/json'}),'omnara-unsaved-draft-'+vault.key+'.json')};
$('#export').onclick=()=>act(()=>download('export','omnara-'+vault.key+'.zip'));$('#handoff').onclick=()=>act(()=>download('handoff','next-research-pass.md'));
const savedSkin=store.get('omnaraSkin');const migratedSkin={aperture:'tracework',marginalia:'surveyfolio',signal:'proofcabinet'}[savedSkin]||savedSkin;$('#skin').value=['tracework','surveyfolio','proofcabinet'].includes(migratedSkin)?migratedSkin:'tracework';document.body.dataset.skin=$('#skin').value;
$('#skin').onchange=e=>{document.body.dataset.skin=e.target.value;requestAnimationFrame(drawConnections);store.set('omnaraSkin',e.target.value);status('Environment · '+e.target.selectedOptions[0].textContent)};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'&&vault){e.preventDefault();if(dirty)act(save)}});
act(async()=>{await list();const last=store.get('omnaraCampaign');if(last&&campaigns.some(x=>x.key===last))await open(last);else if(campaigns.length)await open(campaigns[0].key);else status('Ready for your first investigation')});

function drawConnections(){
  const canvas=$('.map-canvas'),svg=canvas?.querySelector('.map-links');if(!canvas||!svg)return;
  const bounds=canvas.getBoundingClientRect(),claims=rows('claim-ledger.jsonl'),claimById=new Map(claims.map(c=>[c.id,c]));
  const sourceNodes=new Map([...canvas.querySelectorAll('.source-node')].map(n=>[n.dataset.peek,n]));
  svg.setAttribute('viewBox',`0 0 ${bounds.width} ${bounds.height}`);
  const paths=[];
  for(const node of canvas.querySelectorAll('.claim-choice')){
    const c=claimById.get(node.dataset.claim),a=node.getBoundingClientRect();if(!c)continue;
    for(const id of c.source_ids||[]){
      const target=sourceNodes.get(id);if(!target)continue;
      const b=target.getBoundingClientRect(),x1=a.right-bounds.left,y1=a.top+a.height/2-bounds.top,x2=b.left-bounds.left,y2=b.top+b.height/2-bounds.top;
      const active=c.id===selectedClaim||id===selectedSource;
      const d=document.body.dataset.skin==='proofcabinet'?`M${x1} ${y1} H${(x1+x2)/2} V${y2} H${x2}`:`M${x1} ${y1} C${x1+(x2-x1)*.48} ${y1}, ${x2-(x2-x1)*.48} ${y2}, ${x2} ${y2}`;
      paths.push(`<path d="${d}" class="${active?'is-active':'is-context'}" ${active?'stroke-width="2"':'stroke-width="1"'} fill="none"/>`);
    }
  }
  svg.innerHTML=paths.join('');
  canvas.querySelectorAll('.source-node').forEach(n=>n.classList.toggle('is-related',!!claimById.get(selectedClaim)?.source_ids?.includes(n.dataset.peek)));
}
window.addEventListener('resize',()=>{if(tab==='atlas'&&vault)requestAnimationFrame(drawConnections)});





